### ISSUE TITLE
No DefinePlugin

### ISSUE THREAD

**Issue by freecates** [ricokahler/next-plugin-query-cache#1]
Hi,
Afet installing an configuring accoriding to your readme, I get this:

```
ready - started server on http://localhost:3000
[next-plugin-query-cache] Up on port 39733.
> Ready! Available at http://localhost:3000
Error: Could not find DefinePlugin. This is an bug in next-plugin-query-cache.
    at Object.webpack (/home/ramon/Documents/cdbcn/node_modules/next-plugin-query-cache/config.cjs.js:556:19)
    at getBaseWebpackConfig (/home/ramon/Documents/cdbcn/node_modules/next/dist/build/webpack-config.js:138:395)
    at async Promise.all (index 0)
    at async HotReloader.start (/home/ramon/Documents/cdbcn/node_modules/next/dist/server/hot-reloader.js:14:2403)
    at async DevServer.prepare (/home/ramon/Documents/cdbcn/node_modules/next/dist/server/next-dev-server.js:15:414)
    at async /home/ramon/Documents/cdbcn/node_modules/next/dist/cli/next-dev.js:22:1
```

**Comment by ricokahler** [comment]
What version of next.js are you using and do you have any other customizations in next.confg.js?

Could you paste your `next.config.js`?

Side note: I just noticed that error message has a typo haha. I'll have to fix that too

![image](https://user-images.githubusercontent.com/10551026/106494041-e88f4c80-6487-11eb-821e-129e7cc442d6.png)

**Comment by freecates** [comment]
Of course:

```
"next": "10.0.5",
const { createQueryCachePlugin } = require('next-plugin-query-cache/config');

const withQueryCache = createQueryCachePlugin();

module.exports = withQueryCache({
    images: {
        domains: ['i.ytimg.com'],
    },
    i18n: {
        locales: ['ca'],
        defaultLocale: 'ca',
    },
});
```

**Comment by ricokahler** [comment]
No not yet. Apologies.

Been rather busy lately but I can take a look sometime later today.

btw thanks for taking the time to test this lib out in its experimental phase, helps out a ton!

**Comment by freecates** [comment]
I think it will be very useful. It's a common case scenario when doing static props in netxjs. It's a pleasure to test it.

**Comment by ricokahler** [comment]
I definitely see the bug now. I'm not handling the empty webpack config case correctly so it can't find the existing webpack plugins and throws.

You can work around this by providing a no-op webpack config function for now.

```js
const { createQueryCachePlugin } = require('next-plugin-query-cache/config');

const withQueryCache = createQueryCachePlugin();

module.exports = withQueryCache({
    images: {
        domains: ['i.ytimg.com'],
    },
    i18n: {
        locales: ['ca'],
        defaultLocale: 'ca',
    },
    // 👇👇👇
    webpack: config => config,
    // 👆👆👆
});
```

I actually started using this lib at work and I like the result enough where I want to invest the time to polish this thing. I'll try to have a real fix up (along with other repo improvements) this weekend. I'll keep ya posted.

**Comment by ricokahler** [comment]
Hey there @freecates, I just released a stable version of this lib. Let me know what you think!
